#!/usr/bin/env python
# prints bytes for a given value
# ex: ./chr 48 49 0x20 0x50 32 52
import sys
import hex_str

cmode = False

if len(sys.argv) <= 1:
	print "syntax: %s [-C] <bytes/s ...>" % (sys.argv[0])
	print "-C = C string output mode"
	sys.exit(23)
args = sys.argv[1:]
if sys.argv[1] == '-C':
	cmode = True
	args = sys.argv[2:]

s = "".join(args)
s = hex_str.str_to_hex(s)

if cmode:
	sys.stdout.write('"\\x')
	sys.stdout.write(s.lower().replace(" ", "\\x"))
	sys.stdout.write('"')
else:
	sys.stdout.write(s)
print
